# Generated by Django 5.0.2 on 2024-02-19 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('team', models.CharField(max_length=100)),
                ('score', models.IntegerField(default=0)),
                ('percentage_wins', models.IntegerField(default=0)),
            ],
        ),
    ]
